POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "React blogs",
    "author": "n.n",
    "url": "https://reactjs.org/blog",
    "likes": 5,
    "userId": "5bb20889e4a0aa2fb3025f4a"
}